name: news_app_clean_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.9

  #icon
  ionicons: ^0.2.2

  #routing
  go_router: ^14.6.3

  #state management
  flutter_bloc: ^9.1.1

  #comparing dart objects
  equatable: ^2.0.8

  #service locator
  injectable: ^3.0.0
  get_it: ^9.2.1
  
  #dateFormat
  intl: ^0.20.2

  #Database
  drift: ^2.33.0
  drift_flutter: ^0.3.0

  #make request to api
  dio: ^5.9.2
  retrofit: ^4.9.2

  # Firebase
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0
  firebase_storage: ^13.3.0
  firebase_auth: ^6.5.0


  #Hooks
  flutter_hooks: ^0.21.3+1

  #chached image 
  cached_network_image: ^3.4.1
  flutter_quill: ^11.5.0
  image_picker: ^1.2.1
  wakelock_plus: ^1.5.2
  google_fonts: ^8.1.0
  google_sign_in: ^7.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  build_runner: ^2.15.0
  bloc_test: ^10.0.0
  injectable_generator: ^3.0.0
  drift_dev: ^2.33.0
  mocktail: ^1.0.4
  mockito: ^5.5.1
  retrofit_generator: ^10.2.6

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/fonts/google/

 
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
