// Mocks generated by Mockito 5.4.6 from annotations
// in news_app_clean_architecture/test/features/bookmarks/data/repository/bookmark_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:news_app_clean_architecture/features/bookmarks/data/datasources/local/local_bookmarks_datasource.dart'
    as _i2;
import 'package:news_app_clean_architecture/features/bookmarks/data/models/bookmark_model.dart'
    as _i4;
import 'package:news_app_clean_architecture/features/bookmarks/domain/entities/article_source.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LocalBookmarksDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalBookmarksDataSource extends _i1.Mock
    implements _i2.LocalBookmarksDataSource {
  @override
  _i3.Future<List<_i4.BookmarkModel>> getBookmarks() =>
      (super.noSuchMethod(
            Invocation.method(#getBookmarks, []),
            returnValue: _i3.Future<List<_i4.BookmarkModel>>.value(
              <_i4.BookmarkModel>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.BookmarkModel>>.value(
                  <_i4.BookmarkModel>[],
                ),
          )
          as _i3.Future<List<_i4.BookmarkModel>>);

  @override
  _i3.Stream<List<_i4.BookmarkModel>> watchBookmarks() =>
      (super.noSuchMethod(
            Invocation.method(#watchBookmarks, []),
            returnValue: _i3.Stream<List<_i4.BookmarkModel>>.empty(),
            returnValueForMissingStub:
                _i3.Stream<List<_i4.BookmarkModel>>.empty(),
          )
          as _i3.Stream<List<_i4.BookmarkModel>>);

  @override
  _i3.Future<void> addBookmark(_i4.BookmarkModel? bookmark) =>
      (super.noSuchMethod(
            Invocation.method(#addBookmark, [bookmark]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeBookmark(
    String? sourceId,
    _i5.ArticleSource? source,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeBookmark, [sourceId, source]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isBookmarked(String? sourceId, _i5.ArticleSource? source) =>
      (super.noSuchMethod(
            Invocation.method(#isBookmarked, [sourceId, source]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
