import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_quill/flutter_quill.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:news_app_clean_architecture/l10n/generated/app_localizations.dart';
import 'package:news_app_clean_architecture/config/router/app_router.dart';
import 'package:news_app_clean_architecture/core/di/injection.dart';
import 'package:news_app_clean_architecture/features/auth/presentation/bloc/auth_bloc.dart';
import 'package:news_app_clean_architecture/features/bookmarks/presentation/bloc/bookmark_bloc.dart';
import 'package:news_app_clean_architecture/features/bookmarks/presentation/bloc/bookmark_event.dart';
import 'package:news_app_clean_architecture/firebase_options.dart';
import 'package:wakelock_plus/wakelock_plus.dart';
import 'config/theme/app_themes.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  GoogleFonts.config.allowRuntimeFetching = false;

  // ...

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // google_sign_in v7: reads serverClientId automatically from
  // the default_web_client_id resource generated by google-services.json.
  await GoogleSignIn.instance.initialize();

  WakelockPlus.enable();
  await configureDependencies();
  final authBloc = sl<AuthBloc>();
  final bookmarkBloc = sl<BookmarkBloc>()..add(const GetBookmarksEvent());
  AppRouter.instance.init(sl, authBloc: authBloc);
  await GoogleFonts.pendingFonts([
    GoogleFonts.newsreader(),
    GoogleFonts.newsreader(fontWeight: FontWeight.w500),
    GoogleFonts.newsreader(fontWeight: FontWeight.w600),
    GoogleFonts.newsreader(fontWeight: FontWeight.w700),
    GoogleFonts.workSans(),
    GoogleFonts.workSans(fontWeight: FontWeight.w500),
    GoogleFonts.workSans(fontWeight: FontWeight.w600),
    GoogleFonts.workSans(fontWeight: FontWeight.w700),
  ]);

  runApp(MyApp(authBloc: authBloc, bookmarkBloc: bookmarkBloc));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key, required this.authBloc, required this.bookmarkBloc});

  final AuthBloc authBloc;
  final BookmarkBloc bookmarkBloc;

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider.value(value: authBloc),
        BlocProvider.value(value: bookmarkBloc),
      ],
      child: MaterialApp.router(
        onGenerateTitle: (context) => AppLocalizations.of(context)!.appTitle,
        debugShowCheckedModeBanner: false,
        theme: AppTheme.light,
        localizationsDelegates: const [
          ...AppLocalizations.localizationsDelegates,
          FlutterQuillLocalizations.delegate,
        ],
        supportedLocales: AppLocalizations.supportedLocales,
        routerConfig: AppRouter.instance.router,
      ),
    );
  }
}
