// Mocks generated by Mockito 5.4.6 from annotations
// in news_app_clean_architecture/test/features/bookmarks/presentation/bloc/bookmark_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:news_app_clean_architecture/features/bookmarks/domain/entities/bookmark_entity.dart'
    as _i4;
import 'package:news_app_clean_architecture/features/bookmarks/domain/usecases/add_bookmark.dart'
    as _i5;
import 'package:news_app_clean_architecture/features/bookmarks/domain/usecases/bookmark_params.dart'
    as _i6;
import 'package:news_app_clean_architecture/features/bookmarks/domain/usecases/get_bookmarks.dart'
    as _i2;
import 'package:news_app_clean_architecture/features/bookmarks/domain/usecases/remove_bookmark.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [WatchBookmarksUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchBookmarksUseCase extends _i1.Mock
    implements _i2.WatchBookmarksUseCase {
  @override
  _i3.Stream<List<_i4.BookmarkEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Stream<List<_i4.BookmarkEntity>>.empty(),
            returnValueForMissingStub:
                _i3.Stream<List<_i4.BookmarkEntity>>.empty(),
          )
          as _i3.Stream<List<_i4.BookmarkEntity>>);
}

/// A class which mocks [AddBookmarkUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddBookmarkUseCase extends _i1.Mock
    implements _i5.AddBookmarkUseCase {
  @override
  _i3.Future<void> call({_i6.BookmarkParams? params}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [RemoveBookmarkUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveBookmarkUseCase extends _i1.Mock
    implements _i7.RemoveBookmarkUseCase {
  @override
  _i3.Future<void> call({_i6.BookmarkIdentifierParams? params}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
